version: "3.3"

services:
  sketch_engine:
    restart: always
    image: "${IMAGE_NAME:-lcc/nosketch-engine:latest}"
    container_name: "${CONTAINER_NAME:-noske}"
    environment:
      SERVER_NAME: "${SERVER_NAME:-https://cql.wortschatz-leipzig.de/}"
      SERVER_ALIAS: "${SERVER_ALIAS:-cql.wortschatz-leipzig.de}"
      CITATION_LINK: "${CITATION_LINK:-https://wortschatz-leipzig.de/}"
      HTACCESS: "${HTACCESS? Please use export HTACCESS=$(cat secrets/htaccess) or set it as empty!}"
      HTPASSWD: "${HTPASSWD? Please use export HTPASSWD=$(cat secrets/htpasswd) or set it as empty!}"
    volumes:
      - type: bind
        source: "${REGISTRY_DIR:-/disk/NoSketchEngine/registry}"
        target: /corpora/registry
        read_only: true
      - type: bind
        source: "${VERT_DIR:-/disk/NoSketchEngine/vert}"
        target: /corpora/vert
        read_only: true
      - type: bind
        source: "${COMPILED_DIR:-/ssd1/NoSketchEngine/data}"
        target: /corpora/data
        read_only: true
      - type: bind
        source: "${CACHE_DIR:-/ssd1/NoSketchEngine/cache}"
        target: /var/lib/bonito/cache
